_imagine:
    resource: .
    type:     imagine

NewsBundle:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account/profile

PlatformDSpoutletBundle:
    resource: "@SpoutletBundle/Resources/config/routing.yml"
    prefix:   /

PlatformDEventBundle:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /

PlatformDGiveawayBundle:
    resource: "@GiveawayBundle/Resources/config/routing.yml"
    prefix:   /

PlatformDSweepstakesBundle:
    resource: "@SweepstakesBundle/Resources/config/routing.yml"
    prefix:   /

PlatformdTranslationBundle:
    resource: "@TranslationBundle/Resources/config/routing.yml"
    prefix:   /

PlatformDSearchBundle:
    resource: "@SearchBundle/Resources/config/routing.yml"
    prefix:   /

# user bundle stuff
_user_bundle_generic_import:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

GameBundle:
    resource: "@GameBundle/Resources/config/routing.yml"
    prefix:   /

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /theme

VideoBundle:
    resource: "@VideoBundle/Resources/config/routing.yml"
    prefix: /

PlatformDHtmlWidgetBundle:
    resource: "@HtmlWidgetBundle/Resources/config/routing.yml"
    prefix:   /

# This MUST remain last in this list, as it needs to have lowest priority in order to prevent groups pages
# from conflicting with other routes. This facilitates the removal of the /groups prefix on groups urls
PlatformDGroupBundle:
    resource: "@GroupBundle/Resources/config/routing.yml"
    prefix:   /

IdeaBundle:
    resource: "@IdeaBundle/Resources/config/routing.yml"
    prefix:   /

ApiBundle:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api
